package com.manage.book.dal.dataobject;

import java.util.Date;

public class AddressInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.is_default
     *
     * @mbggenerated
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.accept_phone
     *
     * @mbggenerated
     */
    private String acceptPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.accept_name
     *
     * @mbggenerated
     */
    private String acceptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_info.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    public AddressInfoDO(Integer id, Integer userId, String provinceCode, String cityCode, String areaCode, String address, Integer isDefault, String acceptPhone, String acceptName, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.userId = userId;
        this.provinceCode = provinceCode;
        this.cityCode = cityCode;
        this.areaCode = areaCode;
        this.address = address;
        this.isDefault = isDefault;
        this.acceptPhone = acceptPhone;
        this.acceptName = acceptName;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    public AddressInfoDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.id
     *
     * @return the value of address_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.id
     *
     * @param id the value for address_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.user_id
     *
     * @return the value of address_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.user_id
     *
     * @param userId the value for address_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.province_code
     *
     * @return the value of address_info.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.province_code
     *
     * @param provinceCode the value for address_info.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.city_code
     *
     * @return the value of address_info.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.city_code
     *
     * @param cityCode the value for address_info.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.area_code
     *
     * @return the value of address_info.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.area_code
     *
     * @param areaCode the value for address_info.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.address
     *
     * @return the value of address_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.address
     *
     * @param address the value for address_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.is_default
     *
     * @return the value of address_info.is_default
     *
     * @mbggenerated
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.is_default
     *
     * @param isDefault the value for address_info.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.accept_phone
     *
     * @return the value of address_info.accept_phone
     *
     * @mbggenerated
     */
    public String getAcceptPhone() {
        return acceptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.accept_phone
     *
     * @param acceptPhone the value for address_info.accept_phone
     *
     * @mbggenerated
     */
    public void setAcceptPhone(String acceptPhone) {
        this.acceptPhone = acceptPhone == null ? null : acceptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.accept_name
     *
     * @return the value of address_info.accept_name
     *
     * @mbggenerated
     */
    public String getAcceptName() {
        return acceptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.accept_name
     *
     * @param acceptName the value for address_info.accept_name
     *
     * @mbggenerated
     */
    public void setAcceptName(String acceptName) {
        this.acceptName = acceptName == null ? null : acceptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.gmt_create
     *
     * @return the value of address_info.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.gmt_create
     *
     * @param gmtCreate the value for address_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_info.gmt_modified
     *
     * @return the value of address_info.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_info.gmt_modified
     *
     * @param gmtModified the value for address_info.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}