package com.manage.book.dal.dataobject;

import java.util.Date;

public class AppAreaDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.v_code
     *
     * @mbggenerated
     */
    private String vCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.v_pareacode
     *
     * @mbggenerated
     */
    private String vPareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.v_name
     *
     * @mbggenerated
     */
    private String vName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.n_level
     *
     * @mbggenerated
     */
    private Integer nLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.v_upcode
     *
     * @mbggenerated
     */
    private String vUpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.v_status
     *
     * @mbggenerated
     */
    private String vStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.name_initials
     *
     * @mbggenerated
     */
    private String nameInitials;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.isHot
     *
     * @mbggenerated
     */
    private Integer ishot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_area.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    public AppAreaDO(String vCode, String vPareacode, String vName, Integer nLevel, String vUpcode, String vStatus, String nameInitials, Integer ishot, Date gmtModified, Date gmtCreate) {
        this.vCode = vCode;
        this.vPareacode = vPareacode;
        this.vName = vName;
        this.nLevel = nLevel;
        this.vUpcode = vUpcode;
        this.vStatus = vStatus;
        this.nameInitials = nameInitials;
        this.ishot = ishot;
        this.gmtModified = gmtModified;
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    public AppAreaDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.v_code
     *
     * @return the value of app_area.v_code
     *
     * @mbggenerated
     */
    public String getvCode() {
        return vCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.v_code
     *
     * @param vCode the value for app_area.v_code
     *
     * @mbggenerated
     */
    public void setvCode(String vCode) {
        this.vCode = vCode == null ? null : vCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.v_pareacode
     *
     * @return the value of app_area.v_pareacode
     *
     * @mbggenerated
     */
    public String getvPareacode() {
        return vPareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.v_pareacode
     *
     * @param vPareacode the value for app_area.v_pareacode
     *
     * @mbggenerated
     */
    public void setvPareacode(String vPareacode) {
        this.vPareacode = vPareacode == null ? null : vPareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.v_name
     *
     * @return the value of app_area.v_name
     *
     * @mbggenerated
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.v_name
     *
     * @param vName the value for app_area.v_name
     *
     * @mbggenerated
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.n_level
     *
     * @return the value of app_area.n_level
     *
     * @mbggenerated
     */
    public Integer getnLevel() {
        return nLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.n_level
     *
     * @param nLevel the value for app_area.n_level
     *
     * @mbggenerated
     */
    public void setnLevel(Integer nLevel) {
        this.nLevel = nLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.v_upcode
     *
     * @return the value of app_area.v_upcode
     *
     * @mbggenerated
     */
    public String getvUpcode() {
        return vUpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.v_upcode
     *
     * @param vUpcode the value for app_area.v_upcode
     *
     * @mbggenerated
     */
    public void setvUpcode(String vUpcode) {
        this.vUpcode = vUpcode == null ? null : vUpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.v_status
     *
     * @return the value of app_area.v_status
     *
     * @mbggenerated
     */
    public String getvStatus() {
        return vStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.v_status
     *
     * @param vStatus the value for app_area.v_status
     *
     * @mbggenerated
     */
    public void setvStatus(String vStatus) {
        this.vStatus = vStatus == null ? null : vStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.name_initials
     *
     * @return the value of app_area.name_initials
     *
     * @mbggenerated
     */
    public String getNameInitials() {
        return nameInitials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.name_initials
     *
     * @param nameInitials the value for app_area.name_initials
     *
     * @mbggenerated
     */
    public void setNameInitials(String nameInitials) {
        this.nameInitials = nameInitials == null ? null : nameInitials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.isHot
     *
     * @return the value of app_area.isHot
     *
     * @mbggenerated
     */
    public Integer getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.isHot
     *
     * @param ishot the value for app_area.isHot
     *
     * @mbggenerated
     */
    public void setIshot(Integer ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.gmt_modified
     *
     * @return the value of app_area.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.gmt_modified
     *
     * @param gmtModified the value for app_area.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_area.gmt_create
     *
     * @return the value of app_area.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_area.gmt_create
     *
     * @param gmtCreate the value for app_area.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}