package com.manage.book.dal.dataobject;

import java.util.Date;

public class BookTypeDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.v_code
     *
     * @mbggenerated
     */
    private String vCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.v_name
     *
     * @mbggenerated
     */
    private String vName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.n_level
     *
     * @mbggenerated
     */
    private Integer nLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.v_upcode
     *
     * @mbggenerated
     */
    private String vUpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.isdelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;
    
    private Boolean selected;
    

    public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    public BookTypeDO(String vCode, String vName, Integer nLevel, String vUpcode, String isdelete, Date gmtModified, Date gmtCreate) {
        this.vCode = vCode;
        this.vName = vName;
        this.nLevel = nLevel;
        this.vUpcode = vUpcode;
        this.isdelete = isdelete;
        this.gmtModified = gmtModified;
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    public BookTypeDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.v_code
     *
     * @return the value of book_type.v_code
     *
     * @mbggenerated
     */
    public String getvCode() {
        return vCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.v_code
     *
     * @param vCode the value for book_type.v_code
     *
     * @mbggenerated
     */
    public void setvCode(String vCode) {
        this.vCode = vCode == null ? null : vCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.v_name
     *
     * @return the value of book_type.v_name
     *
     * @mbggenerated
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.v_name
     *
     * @param vName the value for book_type.v_name
     *
     * @mbggenerated
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.n_level
     *
     * @return the value of book_type.n_level
     *
     * @mbggenerated
     */
    public Integer getnLevel() {
        return nLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.n_level
     *
     * @param nLevel the value for book_type.n_level
     *
     * @mbggenerated
     */
    public void setnLevel(Integer nLevel) {
        this.nLevel = nLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.v_upcode
     *
     * @return the value of book_type.v_upcode
     *
     * @mbggenerated
     */
    public String getvUpcode() {
        return vUpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.v_upcode
     *
     * @param vUpcode the value for book_type.v_upcode
     *
     * @mbggenerated
     */
    public void setvUpcode(String vUpcode) {
        this.vUpcode = vUpcode == null ? null : vUpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.isdelete
     *
     * @return the value of book_type.isdelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.isdelete
     *
     * @param isdelete the value for book_type.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.gmt_modified
     *
     * @return the value of book_type.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.gmt_modified
     *
     * @param gmtModified the value for book_type.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.gmt_create
     *
     * @return the value of book_type.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.gmt_create
     *
     * @param gmtCreate the value for book_type.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}