/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.manage.book.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * ProjectDO database table: project database table comments: Project This file
 * is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to directory
 * <tt>(project-home)/dalgen</tt>
 * 
 * @author badqiu(zhongxuan)
 *
 */
public class ProjectDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;

	/**
	 * reportDate db_column: reportDate
	 */
	private String reportDate;
	/**
	 * project db_column: project
	 */
	private String project;
	/**
	 * sellnum db_column: sellnum
	 */
	private Double sellnum;
	/**
	 * amount db_column: amount
	 */
	private Double amount;
	/**
	 * area db_column: area
	 */
	private Double area;
	/**
	 * avgprice db_column: avgprice
	 */
	private Double avgprice;
	/**
	 * region db_column: region
	 */
	private String region;
	
	/**
	 * url db_column: url
	 */
	private String url;

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the region
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * @param region
	 *            the region to set
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	public String getReportDate() {
		return this.reportDate;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getProject() {
		return this.project;
	}

	public void setSellnum(Double sellnum) {
		this.sellnum = sellnum;
	}

	public Double getSellnum() {
		return this.sellnum;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setArea(Double area) {
		this.area = area;
	}

	public Double getArea() {
		return this.area;
	}

	public void setAvgprice(Double avgprice) {
		this.avgprice = avgprice;
	}

	public Double getAvgprice() {
		return this.avgprice;
	}

	public String toString() {
		return new ToStringBuilder(this).append("ReportDate", getReportDate())
				.append("Project", getProject())
				.append("Sellnum", getSellnum()).append("Amount", getAmount())
				.append("Area", getArea()).append("Avgprice", getAvgprice())
				.toString();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getReportDate())
				.append(getProject()).toHashCode();
	}

	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (this == obj)
			return true;
		if (obj instanceof ProjectDO == false)
			return false;
		ProjectDO other = (ProjectDO) obj;
		return new EqualsBuilder()
				.append(getReportDate(), other.getReportDate())
				.append(getProject(), other.getProject()).isEquals();
	}
}
