package com.manage.book.dal.dataobject;

import java.util.Date;

public class UserBorrowInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.borrow_time
     *
     * @mbggenerated
     */
    private Date borrowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.borrow_type
     *
     * @mbggenerated
     */
    private Integer borrowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.borrow_status
     *
     * @mbggenerated
     */
    private Integer borrowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_borrow_info.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_borrow_info
     *
     * @mbggenerated
     */
    public UserBorrowInfoDO(Integer userId, Integer bookId, Date borrowTime, Integer borrowType, Integer borrowStatus, Date gmtModified, Date gmtCreate) {
        this.userId = userId;
        this.bookId = bookId;
        this.borrowTime = borrowTime;
        this.borrowType = borrowType;
        this.borrowStatus = borrowStatus;
        this.gmtModified = gmtModified;
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_borrow_info
     *
     * @mbggenerated
     */
    public UserBorrowInfoDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.user_id
     *
     * @return the value of user_borrow_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.user_id
     *
     * @param userId the value for user_borrow_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.book_id
     *
     * @return the value of user_borrow_info.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.book_id
     *
     * @param bookId the value for user_borrow_info.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.borrow_time
     *
     * @return the value of user_borrow_info.borrow_time
     *
     * @mbggenerated
     */
    public Date getBorrowTime() {
        return borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.borrow_time
     *
     * @param borrowTime the value for user_borrow_info.borrow_time
     *
     * @mbggenerated
     */
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.borrow_type
     *
     * @return the value of user_borrow_info.borrow_type
     *
     * @mbggenerated
     */
    public Integer getBorrowType() {
        return borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.borrow_type
     *
     * @param borrowType the value for user_borrow_info.borrow_type
     *
     * @mbggenerated
     */
    public void setBorrowType(Integer borrowType) {
        this.borrowType = borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.borrow_status
     *
     * @return the value of user_borrow_info.borrow_status
     *
     * @mbggenerated
     */
    public Integer getBorrowStatus() {
        return borrowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.borrow_status
     *
     * @param borrowStatus the value for user_borrow_info.borrow_status
     *
     * @mbggenerated
     */
    public void setBorrowStatus(Integer borrowStatus) {
        this.borrowStatus = borrowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.gmt_modified
     *
     * @return the value of user_borrow_info.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.gmt_modified
     *
     * @param gmtModified the value for user_borrow_info.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_borrow_info.gmt_create
     *
     * @return the value of user_borrow_info.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_borrow_info.gmt_create
     *
     * @param gmtCreate the value for user_borrow_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}