package com.manage.book.dal.daointerface;

import com.manage.book.dal.daointerface.extend.AddressInfoDOMapperBase;
import com.manage.book.dal.dataobject.AddressInfoDO;
import java.util.List;

public interface AddressInfoDOMapper extends AddressInfoDOMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    int insert(AddressInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    AddressInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    List<AddressInfoDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressInfoDO record);
}