package com.manage.book.dal.daointerface;

import com.manage.book.dal.daointerface.extend.AppAreaDOMapperBase;
import com.manage.book.dal.dataobject.AppAreaDO;
import java.util.List;

public interface AppAreaDOMapper extends AppAreaDOMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    int insert(AppAreaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    AppAreaDO selectByPrimaryKey(String vCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    List<AppAreaDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppAreaDO record);
}