package com.manage.book.dal.daointerface;

import com.manage.book.dal.daointerface.extend.BookTypeDOMapperBase;
import com.manage.book.dal.dataobject.BookTypeDO;
import java.util.List;

public interface BookTypeDOMapper extends BookTypeDOMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    int insert(BookTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    BookTypeDO selectByPrimaryKey(String vCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    List<BookTypeDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookTypeDO record);
}