/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package com.manage.book.dal.daointerface;
import java.util.List;

import org.springframework.dao.DataAccessException;

import com.manage.book.dal.dataobject.ProjectDO;


/**
 * ProjectDAO
 * database table: project
 * database table comments: Project
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public interface ProjectDAO {


	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         project      WHERE         reportDate = ? and url =?</pre> 
	 */
	public int deleteByDate(String reportdate, String url) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         project         (           reportDate ,project ,sellnum ,amount ,area ,avgprice           )      VALUES         (?,?,?,?,?,?)</pre> 
	 */
	public String insert(ProjectDO project) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         reportDate, project, sellnum, amount, area, avgprice                  FROM         project                WHERE        project = ?</pre> 
	 */
	public List<ProjectDO> queryByProject(String project) throws DataAccessException;


}



