package com.manage.book.dal.daointerface;

import com.manage.book.dal.daointerface.extend.UserBorrowInfoDOMapperBase;
import com.manage.book.dal.dataobject.UserBorrowInfoDO;
import java.util.List;

public interface UserBorrowInfoDOMapper extends UserBorrowInfoDOMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_borrow_info
     *
     * @mbggenerated
     */
    int insert(UserBorrowInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_borrow_info
     *
     * @mbggenerated
     */
    List<UserBorrowInfoDO> selectAll();
}