/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */
 
package com.manage.book.dal.ibatis;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.manage.book.dal.daointerface.ProjectDAO;
import com.manage.book.dal.dataobject.ProjectDO;

/**
 * ProjectDAO
 * database table: project
 * database table comments: Project
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class IbatisProjectDAO extends SqlMapClientDaoSupport implements ProjectDAO {


	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         project      WHERE         reportDate = ? and url=?</pre>
	 */
	@Override
	public int deleteByDate(String reportdate, String url) throws DataAccessException {
		Map<String, String> map = new HashMap<String, String>();
		map.put("reportDate", reportdate);
		map.put("url", url);
		return getSqlMapClientTemplate().delete("dcs.Project.deleteByDate", map);
	}

	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         project         (           reportDate ,project ,sellnum ,amount ,area ,avgprice           )      VALUES         (?,?,?,?,?,?)</pre>
	 */
	@Override
	public String insert(ProjectDO project) throws DataAccessException {
		if(project == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("dcs.Project.insert", project);
		return project.getReportDate();
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         reportDate, project, sellnum, amount, area, avgprice                  FROM         project                WHERE          project = ?</pre>
	 */
	@Override
	public List<ProjectDO> queryByProject(String project) throws DataAccessException {
		Map<String,Object> param = new HashMap<String,Object>();
		param.put("project",project);
		return (List<ProjectDO>)getSqlMapClientTemplate().queryForList("dcs.Project.queryByProject",param);
	}


}

